name: DOCX to Markdown

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx

      - name: Run DOCX to Markdown converter
        run: python docx-to-md.py

      - name: Move converted files to repo root
        run: |
          shopt -s nullglob
          for f in MarkdownOutput/*; do
            mv "$f" .
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.md
          git commit -m "Auto-update Markdown from DOCX" || echo "No changes"

      - name: Push converted Markdown
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          directory: .
          force: false
